apiVersion: v1
kind: Pod
metadata:
  name: build_rush
spec:
  containers:
  - name: almalinux9
    image: localhost/build:latest
    workDir: /build
    command: ['make', '-f', '/src/Makefile']
    volumeMounts:
    - name: hostpath-root
      mountPath: /src
      readOnly: true
    - name: hostpath-dist
      mountPath: /dist
    securityContext:
      seLinuxOptions:
        level: "s0:c42"
  volumes:
  - name: hostpath-root
    hostPath:
      path: ./container_root/src
  - name: hostpath-dist
    hostPath:
      path: ./container_root/dist
  restartPolicy: Never
