apiVersion: v1
kind: Pod
metadata:
  name: build_rush
spec:
  containers:
  - name: almalinux9
    image: localhost/build:latest
    workDir: /build
    command: ['make']
    volumeMounts:
    - name: hostpath-root
      mountPath: /build
    securityContext:
      seLinuxOptions:
        level: "s0:c42"
  volumes:
  - name: hostpath-root
    hostPath:
      path: .
  restartPolicy: Never
