apiVersion: v1
kind: Pod
metadata:
  name: build_rush
spec:
  containers:
  - name: almalinux9
    image: localhost/build:latest
    workingDir: /src
    command: ['make']
    volumeMounts:
    - name: hostpath-root
      mountPath: /src
      readOnly: True
    - name: hostpath-dist
      mountPath: /dist
    securityContext:
      seLinuxOptions:
        level: "s0:c42"
  volumes:
  - name: hostpath-root
    hostPath:
      path: .
  - name: hostpath-dist
    hostpath:
      path: ./dist
  restartPolicy: Never
